disabled = false
languageName = "Русский"
locale = "ru"
title = "Ponfertato"
weight = 1

[params]
copyright = "© 2019-{ year } Ponfertato"
dateFormat = "2 January 2006"
displayName = "RU"
isoCode = "ru"
rtl = false

[params.author]
bio = "Гаджет-мастер, технологический эксперт и преданный картофанатор 🥔 а так же системный администратор Cisco/NauSoft"
headline = "Гаджет-мастер, технологический эксперт и преданный картофанатор 🥔"
image = "img/ponfertato.png"
name = "Кирилл Плотников"
links = [
  { discord = "https://discordapp.com/users/ponfertato" },
  { telegram = "https://t.me/ponfertato" },
  { max = "https://max.ru/u/f9LHodD0cOKnC62lqxLZkv1WjyI_o1sYy9xqQFVTS0sCiILUvOsNqhC5H5s" },
  { vk = "https://vk.ru/ponfertato" },
  { nextcloud = "https://cloud.potatoenergy.ru/u/ponfertato" },
  { bluesky = "https://bsky.app/profile/ponfertato.potatoenergy.ru" },
  { mastodon = "https://social.potatoenergy.ru/@ponfertato" },
  { steam = "https://steamcommunity.com/profiles/ponfertato" },
  { codeberg = "https://codeberg.org/ponfertato" },
  { github = "https://github.com/ponfertato" },
  { gitlab = "https://gitlab.com/ponfertato" },
  { orcid = "https://orcid.org/0009-0008-4939-5484" },
  { email = "mailto:ponfertato@potatoenergy.ru" }
]
