disabled = false
languageName = "English"
locale = "en"
title = "Ponfertato"
weight = 2

[params]
copyright = "© 2019-{ year } Ponfertato"
dateFormat = "2 January 2006"
displayName = "EN"
isoCode = "en"
rtl = false

[params.author]
bio = "Gadget wizard, technology expert and dedicated potato fanatic 🥔 as well as Cisco/NauSoft system administrator"
headline = "Gadget wizard, technology expert and dedicated potato fanatic 🥔"
image = "img/ponfertato.png"
name = "Kirill Plotnikov"
links = [
  { discord = "https://discordapp.com/users/ponfertato" },
  { telegram = "https://t.me/ponfertato" },
  { nextcloud = "https://cloud.potatoenergy.ru/u/ponfertato" },
  { bluesky = "https://bsky.app/profile/ponfertato.potatoenergy.ru" },
  { mastodon = "https://social.potatoenergy.ru/@ponfertato" },
  { x-twitter = "https://x.com/ponfertato" },
  { steam = "https://steamcommunity.com/profiles/ponfertato" },
  { codeberg = "https://codeberg.org/ponfertato" },
  { github = "https://github.com/ponfertato" },
  { gitlab = "https://gitlab.com/ponfertato" },
  { orcid = "https://orcid.org/0009-0008-4939-5484" },
  { email = "mailto:ponfertato@potatoenergy.ru" }
]
