[[main]]
name = "Про меня"
pageRef = "about"
weight = 10

[[main]]
name = "Проекты"
pageRef = "projects"
weight = 20

[[main]]
name = "Главный сайт"
url = "https://potatoenergy.ru/"
weight = 999

[[footer]]
name = "RSS"
url = "/index.xml"
weight = 10
