colorScheme = "slate"
defaultAppearance = "black"
defaultBackgroundImage = "/img/flat-mountains.svg"
enableCodeCopy = true

[header]
layout = "basic"

[homepage]
layout = "background"

[article]
heroStyle = "background"
layoutBackgroundHeaderSpace = false
sharingLinks = [ "bluesky", "mastodon", "telegram", "email"]
showAuthor = true
showAuthorBottom = true
showAuthorsBadges = false
showDate = false
showDateUpdated = false
showHero = true
showReadingTime = false
showTags = true
showTaxonomies = true

[list]
cardView = true
heroStyle = "background"
layoutBackgroundHeaderSpace = false
showTableOfContents = true
groupByYear = false
showHero = true